<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    dsafndioashnfioasdhnfio
</body>
<script>
    var data = [
        [
            {
            "name":"数据结构",
            "teacher":"张亚军",
            "location":"I312",
            "range":"1-7周"
        },{
            "name":"算法设计与分析",
            "teacher":"伍健全",
            "location":"I315",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"操作系统原理",
            "teacher":"张亚军",
            "location":"I312",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        }],
        [
            {
                "name":"",
                "teacher":"",
                "location":"",
                "range":""
            },{
            "name":"算法设计与分析",
            "teacher":"伍健全",
            "location":"I315",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"操作系统原理",
            "teacher":"张亚军",
            "location":"I312",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        }],
        [
            {
                "name":"",
                "teacher":"",
                "location":"",
                "range":""
            },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        }],
        [
            {
                "name":"大学英语",
                "teacher":"严丽",
                "location":"A211",
                "range":"1-17周"
            },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"操作系统原理",
            "teacher":"张亚军",
            "location":"I312",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        }],
        [
            {
                "name":"高等代数I",
                "teacher":"张亮",
                "location":"B212",
                "range":"1-18周"
            },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        },{
            "name":"操作系统原理",
            "teacher":"张亚军",
            "location":"I312",
            "range":"1-7周"
        },{
            "name":"",
            "teacher":"",
            "location":"",
            "range":""
        }]
    ];

    for (index in data) {
        console.log(JSON.stringify(data));
    }
</script>
</html>